### ISSUE TITLE
Enable php5-ldap module 

### ISSUE THREAD

**Issue by upendraq** [Stackato-Apps/phpinfo#1]

**Comment by upendraq** [comment]
php module is not enable. Can you please let us know hoe to enable those.

**Comment by btat** [comment]
I don't quite understand how not having the ldap module enabled is an issue for this example. But to answer your question, how a module is enabled depends on which buildpack is being using. At this point in time, the stackato-3.6 branch is using the built-in version of the [Cloud Foundry php-buildpack](https://github.com/cloudfoundry/php-buildpack/tree/v3.1.0). To enable a module create a directory named `.bp-config` and within that directory a file named `options.json` with the following content

```
{
    "PHP_EXTENSIONS": ["ldap"]
}
```

**Comment by upendraq** [comment]
I am not able to install above cloud foundry php-buildpack. We are using stackato-3.4. Getting following error 
 [stackato[fence.0]] 2015-12-11T09:32:13.000Z: Created Docker container
[stackato[fence.0]] 2015-12-11T09:32:15.000Z: Prepared Docker container
[stackato[dea_ng.0]] 2015-12-11T09:32:16.000Z: Launching web process: $HOME/start.sh
[app.0] 2015-12-11T09:32:16.000Z: setting Default New Relic key
[app.0] 2015-12-11T09:32:16.000Z: /etc/stackato/hooks/pre-running: line 15: [: ==: unary operator expected
[app.0] 2015-12-11T09:32:17.000Z: 01:32:17 httpd | AH00526: Syntax error on line 5 of /home/stackato/app/httpd/conf/httpd.conf:
[app.0] 2015-12-11T09:32:17.000Z: 01:32:17 httpd | DocumentRoot must be a directory
[app.0] 2015-12-11T09:32:17.000Z: 01:32:17 php-fpm | [11-Dec-2015 01:32:17] NOTICE: fpm is running, pid 151
[app.0] 2015-12-11T09:32:17.000Z: 01:32:17 php-fpm | [11-Dec-2015 01:32:17] NOTICE: ready to handle connections
[stackato[dea_ng.0]] 2015-12-11T09:32:17.000Z: Unable to successfully start instance (failed to accept connections within health check timeout)
[stackato[fence.0]] 2015-12-11T09:32:18.000Z: Destroyed Docker container

**Comment by btat** [comment]
The stackato-3.4 branch was using the master branch of Heroku's php buildpack, which should have failed before reaching the point your logs show. Could you post your manifest.yml file for me to verify.
